version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: schedio_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:15
    container_name: schedio_test_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_TEST_USER}
      POSTGRES_PASSWORD: ${DB_TEST_PASS}
      POSTGRES_DB: ${DB_TEST_NAME}
    ports:
      - "5434:5432"

  redis:
    image: redis:7
    container_name: schedio_redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: