export const INDUSTRIES = [
  'Buisness Services',
  'Information Technology',
  'Software Development',
  'Data Analaysis',
  'Artificial Intelligence',
  'Finance & Banking',
  'Healthcare',
  'Education',
  'E-commerce',
  'Retail',
  'Manufacturing',
  'Telecommunications',
  'Construction',
  'Transportation & Logistics',
  'Hospitality & Tourism',
  'Marketing & Advertising',
  'Media & Entertainment',
  'Real Estate',
  'Energy & Utilities',
  'Automation & Robotics',
  'Art & Design',
  'Agriculture',
  'Consulting',
  'Government & Public Sector',
  'Non-Profit',
  'Other',
];
